<?php
/**
 * @File
 * Example custom module for Drupal 8.
 * @author Rakesh James
 */

/**
 * Implementing hook_menu().
 */
function example_menu() {
  // The paths given here need to match the ones in example.routing.yml exactly.
  $items['/admin/reports/kindred'] = array(
    'title' => 'Kindred Data Overview',
    'description' => 'The highlights of what has been collected',
    // The name of the route from example.routing.yml
    'route' => 'kindred.overview',
  );
  return $items;
}

// TODO: look up (referrer, GET) and then INSERT or UPDATE (referrer, GET, count)
// oh shucks, this is a name collision for d7 and d8
